#!/bin/bash

NAME=autovpn
PIDFILE=/var/run/$NAME.pid
USER=user # TODO: 替换用户名
VPNUUID=d31f7890-7a45-4596-ad6d-389059b0cc6c # TODO: 替换UUID
MIN=0
MAX=10

# Include autovpn defaults if available.
test -f /etc/autovpn/config && . /etc/autovpn/config

while [ $MIN -le $MAX ]
do
  if  [[ "$(nmcli con status|grep $VPNUUID)" == "" ]]; then
      echo "Disconnected, trying to reconnect...COUNT:$MIN"
      sleep 1s
      MIN=`expr $MIN + 1`
      su $USER -c "nmcli con up uuid $VPNUUID"
  else
      MIN=0
      echo "Already connected !"
  fi
  sleep 10
done

rm -f $PIDFILE
